name: build and deploy on pr merge to main branch

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  build_and_deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: self-hosted

    env:
      DOCKER_USER: $(echo "${{ secrets.DOCKER_USERNAME }}" | cut -d'@' -f1)
      IMAGE_NAME: my-static-app
      CONTAINER_NAME: my-static-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:latest .
          docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # password: ${{ secrets.SERVER_PASSWORD }}
          # port: ${{ secrets.SERVER_PORT }}
          script: |
            docker pull ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest
            docker stop ${{ env.CONTAINER_NAME }} || true
            docker rm ${{ env.CONTAINER_NAME }} || true
            docker run -d -p 5002:5000 --name ${{ env.CONTAINER_NAME }} ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest
